// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"entdemo/ent/schema","Package":"entdemo/ent","Schemas":[{"name":"User","config":{"Table":""},"fields":[{"name":"site_id","type":{"Type":12,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"position":{"Index":0,"MixedIn":false,"MixinIndex":0},"annotations":{"EntGQL":{"Mapping":["siteId"],"Unbind":true}}}]}],"Features":["sql/execquery","intercept","schema/snapshot","namedges"]}`
