// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in entdemo/ent/runtime.go

const (
	Version = "v0.11.6-0.20230111121502-20d92f240fc6"           // Version of ent codegen.
	Sum     = "h1:bfDkoNMHi2HUHmhIekeiyY6Jboog6CgBLHvp9fn99dM=" // Sum of ent codegen.
)
